### ISSUE TITLE
Setup automatic certificate authority for HTTPS

### ISSUE THREAD

**Issue by shawticus** [XRFoundation/XREngine#1051]
Right now, when dev downloads project and runs, HTTPS throws errors about certificates. This is because the self-signed certificates not having a valid signing certificate authority.
If the certificate authority's (CA) certificate is installed and trusted by the computer, it won't throw these errors and HTTPS will work properly.
DELIVERABLE
Cross-platform solution that sets up self-signed certificates so that we don't have HTTPS errors.

https://github.com/daquinoaldo/https-localhost
https://github.com/DylanPiercey/auto-sni
https://www.npmjs.com/package/nodejs-self-signed-certificate-example
https://github.com/cameronhunter/local-ssl-proxy
https://github.com/christianalfoni/create-ssl-certificate - 
![image](https://user-images.githubusercontent.com/18659318/104607250-4d296980-5689-11eb-999a-870fdece49b4.png)

https://github.com/lukechilds/create-cert
https://github.com/Dexus/pem
https://github.com/smallstep/certificates

┆Issue is synchronized with this [Jira Task](https://laguna.atlassian.net/browse/XR3NGIN-13) by [Unito](https://www.unito.io/learn-more)

**Comment by tanya-vykliuk** [comment]
https://github.com/daquinoaldo/https-localhost
![image](https://user-images.githubusercontent.com/18659318/104607475-895cca00-5689-11eb-9679-c29993d8bd74.png)

**Comment by tarasprystavskyj** [comment]
@Kyle Baran , @shaw.theoverlay.eth 
have question about task with generating certificates. 
@Sergiy came to automatic generation of self signed certificate. 
To accept it developer will  need to accept this exception. 
I suppose most devs have seen this problem before and got used to go around it. 
So I propose to leave it as it is for a quick fix and do not proceed for a proper certificate generation.

https://github.com/xr3ngine/xr3ngine/issues/1051
GitHub
Setup automatic certificate authority for HTTPS · Issue #1051 · xr3...
Right now, when dev downloads project and runs, HTTPS throws errors about certificates. This is because the self-signed certificates not having a valid signing certificate authority. If the certifi...

shaw.theoverlay.ethСьогодні о 23:18
Well, this is more or less what we already have. The issue is 1. going to http:// doesn't work and 2. connecting with a new view always throws error on connect, then error connecting to server, so you need to accept two certs every time
TarasСьогодні о 23:18
Tania told that you had idea to create key for a system. And then sign serticate for a host with this system key.
Why every time? I suppose only one time for new domain and ip?
shaw.theoverlay.ethСьогодні о 23:19
Well if you want to test two clients
Or reset the client, or clear browser cache, etc
Collectively many hours have been spent people running into this bug and coming to me for help
TarasСьогодні о 23:20
Excuse me I'm not aware of all details. But who are aware of details do not have time to talk to you. :slight_smile: So I'm trying to search for a simple solution for this task
I see. So ips and host can be different.
Sergiy had question - how he can change domain of localhost in the project lets say to  xr3ngine-app.test
?
shaw.theoverlay.ethСьогодні о 23:21
That would be with a loopback address
localhost is defined by computer. It's like 127.0.0.1
https://askubuntu.com/questions/444124/how-to-add-a-loopback-interface


https://unix.stackexchange.com/questions/460722/how-to-configure-etc-hosts-properly

**Comment by tarasprystavskyj** [comment]
Let's Sergey for a start deduce this error that the certificate is not accepted by the client.
Because the main problem is that the programmer does not know about it. Not to solve it automatically instead.

as Viacheslav had this coment: 
"the problem of accepting an exception (as it is now) is that when this exception is forgotten by the browser over time, then everything is fine on the client - you see that there is a problem and accept the exception, but there is also localhost: 3030 or 192.164.0.4:3030 and then what on it, the exception disappeared immediately - because this is a server api, just suddenly something stops working and there is no obvious obvious hint that this is a problem with the certificate on the server, and you immediately blame the update on the devs (it turns out that everything works for everyone), then you start checking what you have with your computer, whether your edits have broken it and what is happening in general, and that's good if after 10 minutes in total - you remember --- "it's probably the server certificate is rotten!"

in general, error messages and error handling related to the server are simply absent now, in the near future we will definitely need to build a mechanism to display useful error messages in the spirit of "failed to contact the authentication server", "connection with the server lost", "scene on server does not correspond to the loaded scene "," communication error with the media streaming server ".. and so on"

**Comment by tarasprystavskyj** [comment]
Also from Viacheslav: 
"in general, if we are talking about localhost, then it seems like it should always be considered a secured environment, but not the fact that localhost: 3000 is the same.
if we were raising the server on port 80, then maybe we would not need a certificate and the connection would still be considered secure, but then the api server, which is now at 3030, would still require certification"

"the server itself most likely accepts the certificate, but the browser does not.
this is needed on the client side somewhere in the connections with feathers and the server socket and where there are other connections - everywhere to check that there is a connection error and here there may be an error code and you can understand something, I do not remember which codes are returned there (especially considering that they are returned not by the server but by the browser) ... it may just be blocked there and that's it .. you need to check"
