### ISSUE TITLE
Project API Proposal - RFC

### ISSUE THREAD

**Issue by speigg** [XRFoundation/XREngine#4066]
```ts
// projects/starter/xre.project.ts

import {registerProject} from '@xrengine/projects/register'

registerProject({
    thumbnail: "https://assets.website-files.com/<whatever>.png",
    routes: {
        '/': () => import('@xrengine/client/src/pages/index'),
        '/login': () => import('@xrengine/client/src/pages/login'),
        '/harmony': () => import('@xrengine/client/src/pages/harmony/index'),
        '/admin': () => import('@xrengine/client-core/src/admin/adminRoutes'),
        '/location': () => import('@xrengine/client/src/pages/location/location'),
        '/auth': () => import('@xrengine/client/src/pages/auth/authRoutes'),
        '/editor': () => import('@xrengine/client/src/pages/editor/editor')
    },
    locations: {
        'test': {
            scene: () => import('./scenes/test.world'),
            settings: {}
        }
    }
})
```

Goals:
- Enable isomorphic / single source of truth for project routes
- Enable typed project configurations
- Enable statically defined locations

@josh @shawwwwwwww @mrhegemon @NateTheGreatt

**Comment by HexaField** [comment]
If we do adopt this pattern, it should seperate definitions of scenes and locations such that:
- a location has no requirement to load a scene
- a location can load custom scripts without using a scene
- a scene can have metadata distinct from it's data (such as thumbnails)
- in future, scenes will have a many-to-many rather than one-to-many relation with locations via spatial segmentation
- world data will be distinct from scene data (where scene data is static, world data is dynamic)

I propose an amendment to the proposal as follows:
```ts
// ...

locations: {
    'test': {
        scene: 'empty',
        settings: {}
    }
},
scenes: {
    'empty': {
        scene: () => import('./scenes/test.world'),
        thumbnail: './scenes/test.thumbnail.png',
        metadata: {}
    }
}

// ...
```

**Comment by speigg** [comment]
@HexaField 

> a location has no requirement to load a scene
why would a location not load a scene?

> world data will be distinct from scene data (where scene data is static, world data is dynamic)
can you elaborate? is the shape of this data the same, or different?

**Comment by HexaField** [comment]
@speigg 
> why would a location not load a scene?
Why must a location load a scene? One of our projects currently uses the matchmaker functionality to create tournaments via locations. Ituses the enigne for multiplayer realtime networking state management and events, but does not have a 3d aspect.

> can you elaborate? is the shape of this data the same, or different?

World data I am using to describe data about the world that is due to user interactions, such as objects (like cars, balls etc) being moved from their origin or even spawned in progressively that must persist beyond whatever interaction they have (as distinct from say a golf club, which must have it's instance destroyed upon it's owner leaving the world).

**Comment by speigg** [comment]
> One of our projects currently uses the matchmaker functionality to create tournaments via locations. Ituses the enigne for multiplayer realtime networking state management and events, but does not have a 3d aspect.

Isn’t that a misuse of locations?
Why not route to a custom page that initializes the engine as needed? 

> World data I am using to describe data about the world that is due to user interactions, such as objects (like cars, balls etc) being moved from their origin or even spawned in progressively that must persist beyond whatever interaction they have

Is this different from what we are already doing? Once the scene is instantiated into a world, the objects in that scene should become network objects that are owned by the host

**Comment by HexaField** [comment]
> Isn’t that a misuse of locations?

No, since scenes and locations are distinct. Locations, while not specifically built for this functionality, have now been built out with the matchmaker functionality to take advantage of instance provisioning functionality and the full k8s & agones suite of auto-scaling and instance control.

> Is this different from what we are already doing? Once the scene is instantiated into a world, the objects in that scene should become network objects that are owned by the host

I suppose the distinction may be out of scope for this conversation.

**Comment by HexaField** [comment]
Another question just popped up for me. What should the behavior with regards to truth be for locations? Since locations are stored in the database, we can keep them synced with whatever is in the projects, but this would be rather limiting.

**Comment by speigg** [comment]
You’re right, for locations can be interpreted as multiple sources of truth, which is confusing. The location seeds concept sounds promising, though also seems strange it would automatically affect deployment from inside a scene. How about we convert this proposal into defining location seeds?

**Comment by speigg** [comment]
Locations could also function similarly to routes, where multiple locations with the same name can exist, and only one of those can be “active”.

**Comment by speigg** [comment]
One second thought, you’ve convinced, this isn’t needed. Let’s scrap it.

**Comment by HexaField** [comment]
Consensus! On with the code! 🥳☕
