### ISSUE TITLE
Server side values need to be sourced from the db

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#4299]

**Comment by barankyle** [comment]
All of the config values in server-core/src/appconfig.ts should be sourced first from their respective tables in the database, with the environment variables that they're currently sourced from probably used as a backup only if there isn't a row yet.

A reminder: authentication.authStrategies should ignore emailMagicLink and smsMagicLink, since those are custom methods we're defining for client-side use only.
