### ISSUE TITLE
Abstract channel connection handling

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#4447]
media channel connection is mostly done in the current implementation of harmony, we want to separate this from both harmony and locations, such that it is standalone

https://github.com/XRFoundation/XREngine/tree/dev/packages/client/src/components/Harmony/index.tsx
https://github.com/XRFoundation/XREngine/tree/dev/packages/client/src/pages/location/%5BlocationName%5D.tsx

we want something similar to `NetworkInstanceProvisioning` which abstracts and self contains channel provisioning & connection

**Comment by barankyle** [comment]
Channel connections are connections to gameserver instances that are just running audio/video, not world networking. To test it locally, in addition to running the regular `dev` npm script, you'll need to open a separate tab in the console, go to packages/gameserver, and run `npm run dev-channel`. This will start a second gameserver on port 3032, and the instance provisioning logic will assign all requests locally to port 3032 if it's asked to provision a channel instance.

Channels are the communication thread for some entity. Channels can be one of four types: instance, group, party, and user (i.e. between two friends). Channels also support messaging in chat form; some of the logic on the client side has to keep the active text channel separate from the active audio/video channel, because, like Discord, you can send text messages to any entity you want while an audio/video call is active.

The logic surrounding all of this is a bit special when it comes to instance channels due to how many people's feeds we want to display. If the user is connected to an instance channel, i.e. they're sending/receiving audio/video from other people in a world with them, we limit the number of people they can see/hear to the 8 closest people, which is done by making a call to the instance gameserver running the world networking. You can search for the phrase 'nearbyusers' to find most if not all of the logic that deals with that. We do this because trying to update dozens of users's audio and video feeds, and sending feeds of users who just joined a world to dozens of existing users, is computationally expensive. All other channel types will render everyone else who is connected to that channel server.

When you go to /location/<name>, clicking on the microphone or camera that appears in the top center will turn on audio/video for the instance channel. If you want to test group/party/friend channels, you'll have to open Harmony from a location by clicking the purple speech bubble button in the upper right-hand corner. This is the old version of Harmony; the new version hasn't been integrated with all this channel connection logic yet. 

If an instance call is active, and you click on 'Here' in old Harmony, you should see a box for yourself, plus additional boxes if any other clients are in the instance. If you make and click on a party or group, the text messaging portion will change to that party/group, but your active call will remain on the instance. In order to make a call to a party/group/friend, you have to hang up the instance call, then start a call with the party/group/friend.

**Comment by zulqarnainhanif** [comment]
@HexaField can we close this issue?

**Comment by HexaField** [comment]
> @HexaField can we close this issue?

Yes, thank you
