### ISSUE TITLE
Add scene ECS to database

### ISSUE THREAD

**Issue by HexaField** [XRFoundation/XREngine#5857]
- add two new tables: `entity`, `component` to database
  - `entity` has `scene` association
  - `component` has `entity` and `scene` association
- *.scene.json is no longer a hard convention in projects
- the role of scenes in projects is that they are a seed rather than source of truth
- editor "save scene" prompts which file to save to in the project, rather than explicitly saving to <sceneName>.scene.json

**Comment by speigg** [comment]
If we are going to follow an ECS pattern in the database (and I think we should, as it will enforce strong data normalization), then we need separate tables for each component type that we want to persist. In other words, we shouldn't be storing JSON data as strings in the database. 

Also, we need to figure out where exactly changes should persist; at the scene level? location? instance? I assume we're really talking about persistence for each instance, otherwise changes that happen on one instance would affect all other instances.

**Comment by HexaField** [comment]
why can't we can have a 'type' column that uses the proposed `XRE_WHATEVER` gltf extension standards for each component (currently specced for prefabs, could also be implemented for components, something like `XRE_COMPONENT_TRANSFORM` for example, and have project-namespaced types to avoid interoperability collisions between projects)

**Comment by speigg** [comment]
@HexaField doing it that way forces us to store the component data in JSON or similar format within the database, which makes it difficult to efficiently search against or update.

**Comment by HexaField** [comment]
perhaps we should create a factory that abstracts this for us, since all these will be pre-defined data structures in the engine already - this then enables us to have automatic modularity, composability and extensibility with our ECS storage, that also gracefully fails when a project no longer exists, since it will not know to search data it doesnt know about

**Comment by speigg** [comment]
Follow up from our conversation, we decided:

- We're going to follow a Array of Structure approach for storing Entities/Components in the DB, optimizing for loading scenes rather than updates. This means we really only need an `entity-component` table, with an `id`, `scene-id`, `component-type`, and JSON `component` column. 
- We might need to switch from mariadb to postgres for local dev to properly support JSON in our db. This will allow us to build indexes from JSON keys, where applicable.   AWS Aurora RDB, which we are using for production, is compatible with this.

**Comment by HexaField** [comment]
duplicate https://github.com/XRFoundation/XREngine/issues/6074
