### ISSUE TITLE
[Bug]: Scene reload after updating scene in editor does not restore others' avatars

### ISSUE THREAD

**Issue by barankyle** [XRFoundation/XREngine#6853]
When a scene is saved in the editor and multiple users are in a location of the scene, the scene assets are reloaded, but everyone else's avatars are not, though one's own avatar is. Certainly related to this, everyone else's UserMediaWindow disappears and is not re-rendered.

The media connection is actually still fine, since I've been able to hear people who were talking when these scene updates took place.

**Comment by HexaField** [comment]
I don't think there is a viable solution here that won't still have side affects. The issue is we have no way of identifiying static scene  objects from dynamic scene objects, and dynamic scene objects from dynamic non-scene objects. We can create a few conditions for this, but it will not cover all scenarios.

This will get properly solved when the editor is properly networked, and updates are made in real time rather than upon save.

For now, a flag for a soft scene load and checking for a few components (like avatar etc) should be enough.
