### ISSUE TITLE
[Bug]: default-project does not update when updating engine

### ISSUE THREAD

**Issue by speigg** [XRFoundation/XREngine#7325]
Currently the default-project does not update when updating the engine in deployment.  

The default-project should update automatically when updating the engine version.

**Comment by barankyle** [comment]
This seems to be a problem with avatars. They seem to not be getting updated when a project is updated - they might only be inserted onInstall.

There should be a new field in the avatar table tracking which project, if any, it came from. Then, onUpdate, it checks if there's an avatar with that name from that project. If not, install it; otherwise either update the existing one or skip it.

**Comment by HexaField** [comment]
> 

this field should be on static resources, not the avatar table, but we should only check avatars for now
